const LOGIN_VALIDATION = 'LOGIN_VALIDATION'
const LOGIN_ERROR = 'LOGIN_ERROR'
const lOGIN_SUCCES = 'lOGIN_SUCCES'
const PASSWORD_VALIDATION = 'PASSWORD_VALIDATION'
const PASSWORD_SUCCES = 'PASSWORD_SUCCES'

export {}
